'use client';

import { useEffect, useMemo, useState } from 'react';
import {
  Alert,
  App,
  Badge,
  Button,
  Card,
  Col,
  DatePicker,
  Form,
  Input,
  InputNumber,
  Modal,
  Popconfirm,
  Row,
  Select,
  Space,
  Statistic,
  Table,
  Tag,
  Tooltip,
  Typography,
} from 'antd';
import type { ColumnsType, TablePaginationConfig } from 'antd/es/table';
import {
  CheckCircleOutlined,
  CheckOutlined,
  ClockCircleOutlined,
  CloseOutlined,
  InboxOutlined,
  PrinterOutlined,
  SendOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  SyncOutlined,
  TruckOutlined,
  WarningOutlined,
} from '@ant-design/icons';
import { useAdminIndents, useAdminIndentAction, useWarehouseAvailability, type WarehouseAvailabilityResult } from '@/hooks/useAdminIndents';
import { useAdminBranches } from '@/hooks/useAdminBranches';
import { useSuppliers } from '@/hooks/useSuppliers';
import { useCreatePurchaseOrder } from '@/hooks/usePurchaseOrders';
import { useBrandColors } from '@/hooks/useBrandColors';
import { ApiClientError } from '@/lib/api-client';
import type { StockIndent, StockIndentItem } from '@shared/types/stock-indent';
import { formatMoney } from '@shared/format';

const { Title, Text } = Typography;

type PickupGroup = WarehouseAvailabilityResult['pickupGroups'][number];

function printPickingSlip(groups: PickupGroup[], indentNumber: string | null, destinationBranch: string | null) {
  const win = window.open('', '_blank', 'width=820,height=700');
  if (!win) return;
  const groupRows = groups.map((g) => `
    <div class="group">
      <div class="group-header">
        <div class="wh-name">${g.warehouseName} &mdash; ${g.branchName}</div>
        ${g.branchAddress ? `<div class="addr">${g.branchAddress}${g.branchCity ? `, ${g.branchCity}` : ''}</div>` : ''}
        ${g.branchPhone ? `<div class="addr">Phone: ${g.branchPhone}</div>` : ''}
      </div>
      <table>
        <thead><tr><th>Product</th><th>SKU</th><th>UOM</th><th>Qty to Pick</th></tr></thead>
        <tbody>${g.items.map((it) => `<tr><td>${it.productName}</td><td>${it.productSku}</td><td>${it.productUom}</td><td><strong>${it.pickQty}</strong></td></tr>`).join('')}</tbody>
      </table>
    </div>`).join('');
  const now = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
  win.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Picking Slip — ${indentNumber ?? 'N/A'}</title>
<style>
  body{font-family:Arial,sans-serif;font-size:13px;color:#111;padding:24px;margin:0}
  h1{font-size:20px;margin:0 0 4px}
  .meta{color:#555;font-size:12px;margin-bottom:20px}
  .group{margin-bottom:20px;border:1px solid #ccc;border-radius:6px;overflow:hidden;page-break-inside:avoid}
  .group-header{background:#f3f4f6;padding:10px 14px;border-bottom:1px solid #ddd}
  .wh-name{font-weight:700;font-size:14px}
  .addr{font-size:11px;color:#555;margin-top:2px}
  table{width:100%;border-collapse:collapse}
  th{background:#f9fafb;text-align:left;padding:7px 12px;border-bottom:1px solid #e5e7eb;font-size:12px;font-weight:600}
  td{padding:7px 12px;border-bottom:1px solid #f3f4f6;font-size:13px}
  tr:last-child td{border-bottom:none}
  .footer{margin-top:20px;font-size:11px;color:#999;border-top:1px solid #eee;padding-top:10px}
  .print-btn{margin-top:20px}
  @media print{.print-btn{display:none}}
</style></head><body>
<h1>Picking Slip</h1>
<div class="meta">
  Indent: <strong>${indentNumber ?? 'N/A'}</strong> &nbsp;&bull;&nbsp;
  Deliver to: <strong>${destinationBranch ?? 'N/A'}</strong> &nbsp;&bull;&nbsp;
  Printed: <strong>${now}</strong>
</div>
${groups.length === 0 ? '<p>No warehouse pickup groups available.</p>' : groupRows}
<div class="footer">Generated by Welona Admin &mdash; for driver use only</div>
<div class="print-btn"><button onclick="window.print()" style="padding:8px 20px;font-size:14px;cursor:pointer">&#128438; Print</button></div>
</body></html>`);
  win.document.close();
  setTimeout(() => win.print(), 400);
}

const DISPATCH_METHOD_LABELS: Record<string, string> = {
  company_vehicle: 'Company Vehicle',
  branch_staff_pickup: 'Branch Staff Pickup',
  porter: 'Porter Service',
  rapido: 'Rapido / Bike Delivery',
  courier: 'Courier / Transport',
  other: 'Other',
};

const DISPATCH_METHOD_OPTIONS = [
  { value: 'company_vehicle', label: 'Company Vehicle' },
  { value: 'branch_staff_pickup', label: 'Branch Staff Pickup' },
  { value: 'porter', label: 'Porter Service' },
  { value: 'rapido', label: 'Rapido / Bike Delivery' },
  { value: 'courier', label: 'Courier / Transport' },
  { value: 'other', label: 'Other' },
];

const STATUS_COLOR: Record<string, string> = {
  pending: 'orange',
  approved: 'blue',
  dispatched: 'gold',
  delivered: 'cyan',
  closed: 'green',
  rejected: 'red',
};

const STATUS_ICON: Record<string, React.ReactNode> = {
  pending: <ClockCircleOutlined />,
  approved: <CheckOutlined />,
  dispatched: <TruckOutlined />,
  delivered: <CheckCircleOutlined />,
  closed: <InboxOutlined />,
  rejected: <CloseOutlined />,
};

function fmt(iso: string | null | undefined): string {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

/** Nested section shown when a row is expanded */
function ExpandedRow({ record }: { record: StockIndent }) {
  const colors = useBrandColors();
  const cols: ColumnsType<StockIndentItem> = [
    {
      title: 'Product',
      key: 'product',
      render: (_, r) => (
        <Space direction="vertical" size={0}>
          <Text style={{ fontWeight: 600 }}>{r.product.name}</Text>
          <Text style={{ fontSize: 11, color: colors.text.placeholder }}>{r.product.sku} · {r.product.uom}</Text>
        </Space>
      ),
    },
    { title: 'Requested', dataIndex: 'requestedQty', align: 'center', width: 100 },
    {
      title: 'Approved', dataIndex: 'approvedQty', align: 'center', width: 100,
      render: (v: number | null) => v ?? <Text style={{ color: colors.text.placeholder }}>—</Text>,
    },
    {
      title: 'Rejected',
      key: 'rejected',
      align: 'center',
      width: 120,
      render: (_, r: StockIndentItem) => {
        if (r.rejectedQty == null || r.rejectedQty === 0) return <Text style={{ color: colors.text.placeholder }}>—</Text>;
        return (
          <Tooltip title={r.rejectionReason ?? undefined}>
            <Tag color="red" style={{ cursor: r.rejectionReason ? 'help' : 'default' }}>{r.rejectedQty} ⚠</Tag>
          </Tooltip>
        );
      },
    },
    {
      title: 'Dispatched', dataIndex: 'fulfilledQty', align: 'center', width: 110,
      render: (v: number | null) => v ?? <Text style={{ color: colors.text.placeholder }}>—</Text>,
    },
    {
      title: 'Received', dataIndex: 'receivedQty', align: 'center', width: 100,
      render: (v: number | null) => v ?? <Text style={{ color: colors.text.placeholder }}>—</Text>,
    },
    {
      title: 'Pending',
      key: 'pending',
      align: 'center',
      width: 100,
      render: (_, r: StockIndentItem) => {
        const p = (r.fulfilledQty ?? 0) - (r.receivedQty ?? 0);
        return p > 0 ? <Tag color="orange">{p}</Tag> : <Tag color="green">0</Tag>;
      },
    },
  ];

  const hasDelivery = record.dispatchMethod || record.vehicleNumber || record.driverName || record.driverMobile || record.dispatchedAt || record.expectedDeliveryAt || record.deliveryNotes || record.providerName || record.trackingNumber;
  const isThirdParty = record.dispatchMethod === 'porter' || record.dispatchMethod === 'rapido' || record.dispatchMethod === 'courier';

  return (
    <div style={{ margin: '0 48px', paddingBottom: 12 }}>
      {/* Delivery tracking info */}
      {hasDelivery && (
        <div style={{ marginBottom: 12, padding: '10px 14px', background: '#1a2a1a', border: '1px solid #2d4a2d', borderRadius: 6 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 8 }}>
            <Text style={{ color: '#86efac', fontWeight: 600 }}>Dispatch / Tracking Details</Text>
            {record.dispatchMethod && (
              <Tag color="blue" style={{ fontSize: 12 }}>
                {DISPATCH_METHOD_LABELS[record.dispatchMethod] ?? record.dispatchMethod}
              </Tag>
            )}
          </div>
          <Space size={20} wrap>
            {/* Company Vehicle */}
            {record.vehicleNumber && (
              <span style={{ fontSize: 13 }}>
                <Text style={{ color: colors.text.placeholder }}>Vehicle: </Text>
                <Text strong style={{ color: colors.text.primary }}>{record.vehicleNumber}</Text>
              </span>
            )}
            {/* Driver / Employee / Delivery Person name */}
            {record.driverName && (
              <span style={{ fontSize: 13 }}>
                <Text style={{ color: colors.text.placeholder }}>
                  {record.dispatchMethod === 'branch_staff_pickup' ? 'Employee: ' : isThirdParty ? 'Delivery Person: ' : 'Driver: '}
                </Text>
                <Text strong style={{ color: colors.text.primary }}>{record.driverName}</Text>
              </span>
            )}
            {/* Employee ID (branch staff pickup) */}
            {record.pickupEmployeeId && (
              <span style={{ fontSize: 13 }}>
                <Text style={{ color: colors.text.placeholder }}>Emp ID: </Text>
                <Text strong style={{ color: colors.text.primary }}>{record.pickupEmployeeId}</Text>
              </span>
            )}
            {/* Mobile */}
            {record.driverMobile && (
              <span style={{ fontSize: 13 }}>
                <Text style={{ color: colors.text.placeholder }}>Mobile: </Text>
                <Text strong style={{ color: colors.text.primary }}>{record.driverMobile}</Text>
              </span>
            )}
            {/* Provider (porter/rapido/courier) */}
            {record.providerName && (
              <span style={{ fontSize: 13 }}>
                <Text style={{ color: colors.text.placeholder }}>Provider: </Text>
                <Text strong style={{ color: colors.text.primary }}>{record.providerName}</Text>
              </span>
            )}
            {/* Tracking number */}
            {record.trackingNumber && (
              <span style={{ fontSize: 13 }}>
                <Text style={{ color: colors.text.placeholder }}>Tracking: </Text>
                <Text strong style={{ color: colors.text.primary }}>{record.trackingNumber}</Text>
              </span>
            )}
            {/* Delivery charges */}
            {record.deliveryCharges != null && (
              <span style={{ fontSize: 13 }}>
                <Text style={{ color: colors.text.placeholder }}>Charges: </Text>
                <Text strong style={{ color: colors.text.primary }}>{formatMoney(record.deliveryCharges)}</Text>
              </span>
            )}
            {/* Other: custom method name */}
            {record.customMethodName && (
              <span style={{ fontSize: 13 }}>
                <Text style={{ color: colors.text.placeholder }}>Method: </Text>
                <Text strong style={{ color: colors.text.primary }}>{record.customMethodName}</Text>
              </span>
            )}
            {record.dispatchedAt && (
              <span style={{ fontSize: 13 }}>
                <Text style={{ color: colors.text.placeholder }}>Dispatched: </Text>
                <Text strong style={{ color: colors.text.primary }}>{fmt(record.dispatchedAt)}</Text>
              </span>
            )}
            {record.expectedDeliveryAt && (
              <span style={{ fontSize: 13 }}>
                <Text style={{ color: colors.text.placeholder }}>
                  {record.dispatchMethod === 'branch_staff_pickup' ? 'Pickup Time: ' : 'Expected: '}
                </Text>
                <Text strong style={{ color: '#86efac' }}>{fmt(record.expectedDeliveryAt)}</Text>
              </span>
            )}
            {record.deliveryNotes && (
              <span style={{ fontSize: 13 }}>
                <Text style={{ color: colors.text.placeholder }}>
                  {record.dispatchMethod === 'other' ? 'Remarks: ' : 'Notes: '}
                </Text>
                <Text style={{ color: colors.text.primary }}>{record.deliveryNotes}</Text>
              </span>
            )}
          </Space>
        </div>
      )}

      {/* Items table */}
      {record.items.length === 0 ? (
        <Text style={{ color: colors.text.placeholder, padding: 8 }}>No items (legacy record)</Text>
      ) : (
        <Table<StockIndentItem>
          rowKey="id"
          columns={cols}
          dataSource={record.items}
          pagination={false}
          size="small"
        />
      )}
    </div>
  );
}

export default function StockRequestsPage() {
  const colors = useBrandColors();
  const { message } = App.useApp();

  // ── Filters ──────────────────────────────────────────────────────────────
  const [status, setStatus] = useState<string | undefined>(undefined);
  const [branchId, setBranchId] = useState<string | undefined>(undefined);
  const [page, setPage] = useState(1);
  const [limit, setLimit] = useState(20);

  // ── Modal state ──────────────────────────────────────────────────────────
  const [approveTarget, setApproveTarget] = useState<StockIndent | null>(null);
  const [dispatchTarget, setDispatchTarget] = useState<StockIndent | null>(null);
  const [dispatchSelections, setDispatchSelections] = useState<Record<string, string>>({});
  const [slipTarget, setSlipTarget] = useState<StockIndent | null>(null);
  // itemId → warehouseId chosen by the user in the picking slip modal
  const [slipSelections, setSlipSelections] = useState<Record<string, string>>({});

  // Approve qty state — replaces the old approveForm
  const [approveQtys, setApproveQtys] = useState<Record<string, number>>({});
  const [approveReasons, setApproveReasons] = useState<Record<string, string>>({});
  const [approveNotes, setApproveNotes] = useState('');

  const [dispatchForm] = Form.useForm();
  const selectedDispatchMethod = Form.useWatch('dispatchMethod', dispatchForm) as string | undefined;

  // ── PO creation modal state ───────────────────────────────────────────────
  const [poModalOpen, setPoModalOpen] = useState(false);
  const [poIndentRef, setPoIndentRef] = useState<StockIndent | null>(null);
  type InsufficientItem = WarehouseAvailabilityResult['items'][number];
  const [poItemsForOrder, setPoItemsForOrder] = useState<InsufficientItem[]>([]);
  const [poForm] = Form.useForm();


  // ── Data ─────────────────────────────────────────────────────────────────
  const { data, isLoading, refetch } = useAdminIndents({ status, branchId, page, limit });
  const { data: pendingData } = useAdminIndents({ status: 'pending', limit: 1 });
  const { data: approvedData } = useAdminIndents({ status: 'approved', limit: 1 });
  const { data: dispatchedData } = useAdminIndents({ status: 'dispatched', limit: 1 });
  const { data: receivedData } = useAdminIndents({ status: 'delivered', limit: 1 });
  const { data: branchesData } = useAdminBranches({ limit: 200 });
  const { data: suppliersData } = useSuppliers({ limit: 200 });
  const indentAction = useAdminIndentAction();
  const createPO = useCreatePurchaseOrder();
  const { data: approveAvailability, isLoading: approveWhLoading } = useWarehouseAvailability(approveTarget?.id ?? null);
  const { data: warehouseAvailability, isLoading: warehouseLoading } = useWarehouseAvailability(dispatchTarget?.id ?? null);
  const { data: slipAvailability, isLoading: slipLoading } = useWarehouseAvailability(slipTarget?.id ?? null);

  const branchOptions = useMemo(
    () => (branchesData?.items ?? []).map((b) => ({ value: b.id, label: b.branchName })),
    [branchesData],
  );

  const supplierOptions = useMemo(
    () => (suppliersData?.items ?? []).filter((s) => s.isActive).map((s) => ({ value: s.id, label: s.name })),
    [suppliersData],
  );

  // Items in the dispatch modal that don't have enough stock in the selected warehouse
  const insufficientItems = useMemo(() => {
    if (!warehouseAvailability || !dispatchTarget) return [];
    return warehouseAvailability.items.filter((avail) => {
      const selectedWhId = dispatchSelections[avail.itemId] ?? avail.recommendation?.warehouseId;
      if (!selectedWhId) return true;
      const wh = avail.warehouses.find((w) => w.warehouseId === selectedWhId);
      return !wh || wh.quantity < avail.neededQty;
    });
  }, [warehouseAvailability, dispatchSelections, dispatchTarget]);

  const hasInsufficientStock = insufficientItems.length > 0;

  // Init approve qtys when approve modal opens
  useEffect(() => {
    if (!approveTarget) return;
    const init: Record<string, number> = {};
    for (const it of approveTarget.items) init[it.id] = it.requestedQty;
    setApproveQtys(init);
    setApproveReasons({});
    setApproveNotes('');
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [approveTarget?.id]);

  // Init per-item warehouse selections for dispatch from recommendations
  useEffect(() => {
    if (!warehouseAvailability) return;
    const initial: Record<string, string> = {};
    for (const item of warehouseAvailability.items) {
      if (item.recommendation) initial[item.itemId] = item.recommendation.warehouseId;
    }
    setDispatchSelections(initial);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [warehouseAvailability?.indentId]);

  // Init per-item warehouse selections in picking slip modal from recommendations
  useEffect(() => {
    if (!slipAvailability) return;
    const initial: Record<string, string> = {};
    for (const item of slipAvailability.items) {
      if (item.recommendation) initial[item.itemId] = item.recommendation.warehouseId;
    }
    setSlipSelections(initial);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [slipAvailability?.indentId]);

  // Recompute pickup groups from the user's per-item warehouse selections
  const computedPickupGroups = useMemo<PickupGroup[]>(() => {
    if (!slipAvailability) return [];
    const groups: Record<string, PickupGroup> = {};
    for (const item of slipAvailability.items) {
      const whId = slipSelections[item.itemId] ?? item.recommendation?.warehouseId;
      if (!whId) continue;
      const wh = item.warehouses.find((w) => w.warehouseId === whId);
      if (!wh) continue;
      if (!groups[whId]) {
        groups[whId] = {
          warehouseId: whId,
          warehouseName: wh.warehouseName,
          branchName: wh.branchName,
          branchAddress: wh.branchAddress,
          branchCity: wh.branchCity,
          branchPhone: wh.branchPhone,
          items: [],
        };
      }
      groups[whId].items.push({
        productName: item.productName,
        productSku: item.productSku,
        productUom: item.productUom,
        pickQty: item.neededQty,
      });
    }
    return Object.values(groups);
  }, [slipAvailability, slipSelections]);

  // ── Action handler ────────────────────────────────────────────────────────
  const runAction = async (payload: Parameters<typeof indentAction.mutateAsync>[0], successMsg: string) => {
    try {
      await indentAction.mutateAsync(payload);
      message.success(successMsg);
    } catch (err) {
      message.error(err instanceof ApiClientError ? err.message : 'Action failed.');
    }
  };

  // ── Approve ────────────────────────────────────────────────────────────────
  const handleApprove = async () => {
    if (!approveTarget) return;
    const items = approveTarget.items.map((it) => ({
      itemId: it.id,
      approvedQty: approveQtys[it.id] ?? it.requestedQty,
      rejectionReason: approveReasons[it.id] || undefined,
    }));
    const needsReason = items.filter((i) => {
      const orig = approveTarget.items.find((it) => it.id === i.itemId)!;
      return i.approvedQty < orig.requestedQty && !i.rejectionReason;
    });
    if (needsReason.length > 0) {
      message.error('Please enter a reason for any partially approved items.');
      return;
    }
    await runAction(
      { id: approveTarget.id, action: 'approve', items, notes: approveNotes || undefined },
      'Request approved.',
    );
    await refetch();
    setApproveTarget(null);
    setApproveQtys({});
    setApproveReasons({});
    setApproveNotes('');
  };

  // ── Dispatch ──────────────────────────────────────────────────────────────
  const handleDispatch = async () => {
    if (!dispatchTarget) return;
    const values = await dispatchForm.validateFields();
    await runAction(
      {
        id: dispatchTarget.id,
        action: 'dispatch',
        dispatchMethod: values.dispatchMethod,
        items: dispatchTarget.items.map((it, idx) => ({
          itemId: it.id,
          fulfilledQty: values.items[idx].fulfilledQty,
          warehouseId: dispatchSelections[it.id] || undefined,
        })),
        vehicleNumber: values.vehicleNumber || undefined,
        driverName: values.driverName || undefined,
        driverMobile: values.driverMobile || undefined,
        pickupEmployeeId: values.pickupEmployeeId || undefined,
        providerName: values.providerName || undefined,
        trackingNumber: values.trackingNumber || undefined,
        deliveryCharges: values.deliveryCharges != null ? Math.round(values.deliveryCharges * 100) : undefined,
        customMethodName: values.customMethodName || undefined,
        expectedDeliveryAt: values.expectedDeliveryAt?.toISOString(),
        deliveryNotes: values.deliveryNotes || undefined,
      },
      'Dispatched successfully. Awaiting branch receipt.',
    );
    setDispatchTarget(null);
    setDispatchSelections({});
    dispatchForm.resetFields();
  };

  // ── Create PO for missing stock ───────────────────────────────────────────
  const openPoModal = () => {
    setPoIndentRef(dispatchTarget);
    setPoItemsForOrder(insufficientItems);
    poForm.setFieldsValue({
      branchId: undefined,
      supplierId: undefined,
      notes: `Restock for indent ${dispatchTarget?.number ?? ''}`,
      items: insufficientItems.map((item) => ({
        productId: item.productId,
        quantity: item.neededQty,
        unitPrice: 0,
        taxRate: 0,
      })),
    });
    setPoModalOpen(true);
  };

  const handleCreatePO = async () => {
    const values = await poForm.validateFields();
    try {
      const po = await createPO.mutateAsync({
        branchId: values.branchId,
        supplierId: values.supplierId,
        notes: values.notes || undefined,
        items: (values.items as Array<{ productId: string; quantity: number; unitPrice?: number; taxRate?: number }>).map((item) => ({
          productId: item.productId,
          quantity: item.quantity,
          unitPrice: Math.round((item.unitPrice ?? 0) * 100),
          taxRate: Math.round((item.taxRate ?? 0) * 100),
        })),
      });
      message.success(`Purchase Order ${po.number} created. Receive a GRN to add stock, then return here to dispatch.`);
      setPoModalOpen(false);
      setDispatchTarget(null);
      setDispatchSelections({});
      dispatchForm.resetFields();
      poForm.resetFields();
    } catch (err) {
      message.error(err instanceof ApiClientError ? err.message : 'Failed to create purchase order.');
    }
  };

  // ── Table columns ─────────────────────────────────────────────────────────
  const columns: ColumnsType<StockIndent> = useMemo(
    () => [
      {
        title: 'Indent #',
        dataIndex: 'number',
        width: 110,
        render: (v: string | null) => (
          <Text style={{ fontWeight: 700, fontFamily: 'monospace', fontSize: 13, color: colors.gold.primary }}>{v ?? '—'}</Text>
        ),
      },
      {
        title: 'Date',
        dataIndex: 'createdAt',
        width: 150,
        sorter: (a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime(),
        defaultSortOrder: 'descend',
        render: (v: string) => <Text style={{ fontSize: 12, color: colors.text.placeholder }}>{fmt(v)}</Text>,
      },
      {
        title: 'Branch',
        dataIndex: 'branchName',
        width: 160,
        render: (v: string) => (
          <Tag icon={<ShopOutlined />} color={colors.gold.primary} style={{ color: colors.text.onGold, border: 'none', fontSize: 12 }}>
            {v}
          </Tag>
        ),
      },
      {
        title: 'Items',
        key: 'items',
        width: 110,
        align: 'center',
        render: (_, row) => (
          <Space size={4}>
            <Badge count={row.items.length} color={colors.gold.primary} style={{ color: colors.text.onGold }} />
            {row.items.length > 1 && (
              <Tag color="purple" style={{ margin: 0, fontSize: 10, padding: '0 5px', lineHeight: '18px' }}>Bulk</Tag>
            )}
          </Space>
        ),
      },
      {
        title: 'Requested',
        key: 'requestedQty',
        width: 100,
        align: 'center',
        render: (_, row) => {
          const total = row.items.reduce((s, it) => s + it.requestedQty, 0);
          return row.items.length ? <Text style={{ fontWeight: 600 }}>{total}</Text> : '—';
        },
      },
      {
        title: 'Approved',
        key: 'approvedQty',
        width: 100,
        align: 'center',
        render: (_, row) => {
          const hasApproved = row.items.some((it) => it.approvedQty != null);
          if (!hasApproved) return <Text style={{ color: colors.text.placeholder }}>—</Text>;
          const total = row.items.reduce((s, it) => s + (it.approvedQty ?? 0), 0);
          const requested = row.items.reduce((s, it) => s + it.requestedQty, 0);
          const color = total < requested ? '#f97316' : '#22c55e';
          return <Text style={{ fontWeight: 600, color }}>{total}</Text>;
        },
      },
      {
        title: 'Status',
        dataIndex: 'status',
        width: 130,
        render: (v: string) => (
          <Tag icon={STATUS_ICON[v]} color={STATUS_COLOR[v] ?? 'default'} style={{ fontSize: 12 }}>
            {v.charAt(0).toUpperCase() + v.slice(1)}
          </Tag>
        ),
      },
      {
        title: 'Dispatched',
        dataIndex: 'dispatchedAt',
        width: 140,
        render: (v: string | null) => (
          <Text style={{ fontSize: 12, color: colors.text.placeholder }}>{fmt(v)}</Text>
        ),
      },
      {
        title: 'Delivered',
        dataIndex: 'receivedAt',
        width: 140,
        render: (v: string | null) => (
          <Text style={{ fontSize: 12, color: colors.text.placeholder }}>{fmt(v)}</Text>
        ),
      },
      {
        title: 'Actions',
        key: 'actions',
        width: 200,
        render: (_, row) => {
          const busy = indentAction.isPending;
          if (row.status === 'closed' || row.status === 'rejected') {
            return <Text style={{ color: colors.text.placeholder, fontSize: 12 }}>—</Text>;
          }
          return (
            <Space size={4} wrap>
              {row.status === 'pending' && (
                <>
                  <Button
                    size="small" type="primary" icon={<CheckOutlined />}
                    style={{ background: '#22c55e', borderColor: '#22c55e' }}
                    onClick={() => setApproveTarget(row)}
                  >
                    Approve
                  </Button>
                  <Popconfirm title="Reject this request?" okText="Reject" okButtonProps={{ danger: true }} onConfirm={() => runAction({ id: row.id, action: 'reject' }, 'Request rejected.')}>
                    <Button size="small" danger icon={<CloseOutlined />} loading={busy}>Reject</Button>
                  </Popconfirm>
                </>
              )}
              {row.status === 'approved' && (
                <>
                  <Tooltip title="Dispatch items to branch from warehouse stock">
                    <Button
                      size="small" type="primary" icon={<TruckOutlined />}
                      onClick={() => {
                        setDispatchTarget(row);
                        setDispatchSelections({});
                        dispatchForm.setFieldsValue({
                          dispatchMethod: 'company_vehicle',
                          items: row.items.map((it) => ({ fulfilledQty: it.approvedQty ?? it.requestedQty })),
                        });
                      }}
                    >
                      Dispatch
                    </Button>
                  </Tooltip>
                  <Tooltip title="View warehouse pickup details and print picking slip">
                    <Button size="small" icon={<PrinterOutlined />} onClick={() => setSlipTarget(row)}>
                      Slip
                    </Button>
                  </Tooltip>
                  <Popconfirm title="Reject this request?" okText="Reject" okButtonProps={{ danger: true }} onConfirm={() => runAction({ id: row.id, action: 'reject' }, 'Request rejected.')}>
                    <Button size="small" danger icon={<CloseOutlined />} loading={busy}>Reject</Button>
                  </Popconfirm>
                </>
              )}
              {row.status === 'dispatched' && (
                <Tag color="gold" icon={<TruckOutlined />} style={{ fontSize: 12 }}>In Transit</Tag>
              )}
              {row.status === 'delivered' && (
                <Popconfirm title="Close this request?" okText="Close" onConfirm={() => runAction({ id: row.id, action: 'close' }, 'Request closed.')}>
                  <Button size="small" icon={<InboxOutlined />} loading={busy}>Close</Button>
                </Popconfirm>
              )}
            </Space>
          );
        },
      },
    ],
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [colors, indentAction.isPending],
  );

  const pagination: TablePaginationConfig = {
    current: page, pageSize: limit, total: data?.meta.total ?? 0,
    showSizeChanger: true, pageSizeOptions: [20, 50, 100],
    onChange: (next, size) => { setPage(next); if (size !== limit) setLimit(size); },
    showTotal: (t, r) => `${r[0]}â€“${r[1]} of ${t} request${t === 1 ? '' : 's'}`,
  };

  return (
    <div>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 16, flexWrap: 'wrap', gap: 12 }}>
        <div>
          <Title level={3} style={{ color: colors.text.primary, marginBottom: 4 }}>Stock Requests</Title>
          <Text style={{ color: colors.text.placeholder }}>Branch stock requests — approve, dispatch, and confirm receipt to update inventory.</Text>
        </div>
        <Button icon={<SyncOutlined />} onClick={() => refetch()} style={{ borderColor: colors.border, color: colors.text.secondary }}>
          Refresh
        </Button>
      </div>

      {/* Stat cards */}
      <Row gutter={[12, 12]} style={{ marginBottom: 16 }}>
        {[
          { label: 'PENDING', value: pendingData?.meta.total ?? 0, color: '#f97316', badge: 'orange', filter: 'pending' },
          { label: 'APPROVED', value: approvedData?.meta.total ?? 0, color: '#3b82f6', badge: 'blue', filter: 'approved' },
          { label: 'DISPATCHED', value: dispatchedData?.meta.total ?? 0, color: '#d97706', badge: 'gold', filter: 'dispatched' },
          { label: 'DELIVERED', value: receivedData?.meta.total ?? 0, color: '#0891b2', badge: 'cyan', filter: 'delivered' },
        ].map((s) => (
          <Col xs={12} sm={6} key={s.filter}>
            <Card
              size="small"
              style={{ background: colors.black.secondary, border: `1px solid ${colors.border}`, cursor: 'pointer' }}
              styles={{ body: { padding: '12px 16px' } }}
              onClick={() => { setStatus(s.filter); setPage(1); }}
            >
              <Statistic
                title={<span style={{ color: colors.text.placeholder, fontSize: 12 }}>{s.label}</span>}
                value={s.value}
                prefix={<Badge color={s.badge} />}
                valueStyle={{ color: s.color, fontWeight: 700 }}
              />
            </Card>
          </Col>
        ))}
      </Row>

      <Card style={{ background: colors.black.secondary, border: `1px solid ${colors.border}` }} styles={{ body: { padding: 16 } }}>
        {/* Filters */}
        <Row gutter={12} style={{ marginBottom: 16 }} wrap>
          <Col>
            <Select
              showSearch allowClear placeholder="All Branches" style={{ minWidth: 220 }}
              options={branchOptions} value={branchId || undefined}
              onChange={(v) => { setBranchId(v || undefined); setPage(1); }}
              filterOption={(i, o) => (o?.label ?? '').toLowerCase().includes(i.toLowerCase())}
            />
          </Col>
          <Col>
            <Select
              allowClear placeholder="All Statuses" style={{ minWidth: 160 }}
              value={status} onChange={(v) => { setStatus(v); setPage(1); }}
              options={[
                { value: 'pending', label: 'Pending' },
                { value: 'approved', label: 'Approved' },
                { value: 'dispatched', label: 'Dispatched' },
                { value: 'delivered', label: 'Delivered' },
                { value: 'closed', label: 'Closed' },
                { value: 'rejected', label: 'Rejected' },
              ]}
            />
          </Col>
        </Row>

        <Table<StockIndent>
          rowKey="id"
          loading={isLoading}
          columns={columns}
          dataSource={data?.items ?? []}
          pagination={pagination}
          size="middle"
          scroll={{ x: 1100 }}
          expandable={{
            expandedRowRender: (record) => <ExpandedRow record={record} />,
            rowExpandable: () => true,
          }}
        />
      </Card>

      {/* ── Approve Modal ─────────────────────────────────────────────────── */}
      <Modal
        title={`Approve Request${approveTarget?.number ? ` — ${approveTarget.number}` : ''}`}
        open={!!approveTarget}
        onCancel={() => { setApproveTarget(null); setApproveQtys({}); setApproveReasons({}); setApproveNotes(''); }}
        onOk={handleApprove}
        okText="Approve"
        okButtonProps={{ style: { background: '#22c55e', borderColor: '#22c55e' } }}
        confirmLoading={indentAction.isPending}
        width={660}
        destroyOnClose
      >
        {/* Warehouse stock availability */}
        {approveTarget && (
          <div style={{ marginBottom: 16, border: `1px solid ${colors.border}`, borderRadius: 6, overflow: 'hidden' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 12px', borderBottom: `1px solid ${colors.border}`, flexWrap: 'wrap', gap: 8 }}>
              <Space>
                <Text strong style={{ color: colors.text.primary }}>Warehouse Stock</Text>
                {approveWhLoading && <Text style={{ color: colors.text.placeholder, fontSize: 12 }}>Checking…</Text>}
              </Space>
              {approveAvailability && (
                <Button
                  size="small"
                  icon={<PrinterOutlined />}
                  onClick={() => printPickingSlip(approveAvailability.pickupGroups, approveTarget.number ?? null, approveTarget.branchName ?? null)}
                >
                  Print Picking Slip
                </Button>
              )}
            </div>
            {/* Column headers */}
            {approveAvailability && approveAvailability.items.length > 0 && (
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '5px 12px', borderBottom: `1px solid ${colors.border}`, background: 'rgba(0,0,0,0.15)' }}>
                <span style={{ flex: 1, fontSize: 11, color: colors.text.placeholder, fontWeight: 600 }}>PRODUCT</span>
                <span style={{ width: 56, textAlign: 'center', fontSize: 11, color: colors.text.placeholder, fontWeight: 600 }}>NEEDED</span>
                <span style={{ width: 88, fontSize: 11, color: colors.gold?.primary ?? '#d4a017', fontWeight: 700 }}>APPROVE QTY</span>
                <span style={{ width: 72, textAlign: 'center', fontSize: 11, color: colors.text.placeholder, fontWeight: 600 }}>IN STOCK</span>
                <span style={{ flex: 1, fontSize: 11, color: colors.text.placeholder, fontWeight: 600 }}>BEST WAREHOUSE</span>
              </div>
            )}
            {approveAvailability?.items.map((avail, idx) => {
              const rec = avail.recommendation;
              const totalAvailable = avail.warehouses.reduce((s, w) => s + w.quantity, 0);
              const canFulfill = rec?.canFullyFulfill ?? false;
              const partial = !canFulfill && totalAvailable > 0;
              const isLast = idx === (approveAvailability.items.length - 1);
              return (
                <div key={avail.itemId} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '8px 12px', borderBottom: isLast ? 'none' : `1px solid ${colors.border}` }}>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <Text style={{ color: colors.text.primary, fontWeight: 600, fontSize: 13, display: 'block', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{avail.productName}</Text>
                    <Text style={{ color: colors.text.placeholder, fontSize: 11 }}>{avail.productSku}</Text>
                  </div>
                  <div style={{ width: 56, textAlign: 'center' }}>
                    <Text style={{ color: colors.text.primary, fontWeight: 700, fontSize: 13 }}>{avail.requestedQty}</Text>
                  </div>
                  {/* APPROVE QTY — entered by admin */}
                  <div style={{ width: 88 }}>
                    <Input
                      size="small"
                      value={(approveQtys[avail.itemId] ?? avail.requestedQty).toString()}
                      onChange={(e) => {
                        const n = parseInt(e.target.value, 10);
                        setApproveQtys((prev) => ({ ...prev, [avail.itemId]: isNaN(n) ? 0 : Math.min(n, avail.requestedQty) }));
                      }}
                      style={{ width: 60, textAlign: 'right' }}
                    />
                    {(approveQtys[avail.itemId] ?? avail.requestedQty) < avail.requestedQty && (
                      <Input
                        size="small"
                        placeholder="Reason…"
                        value={approveReasons[avail.itemId] ?? ''}
                        onChange={(e) => setApproveReasons((prev) => ({ ...prev, [avail.itemId]: e.target.value }))}
                        status={!approveReasons[avail.itemId] ? 'error' : undefined}
                        style={{ width: '100%', marginTop: 4, fontSize: 11 }}
                      />
                    )}
                  </div>
                  <div style={{ width: 72, textAlign: 'center' }}>
                    <Tag
                      color={canFulfill ? 'green' : partial ? 'orange' : 'red'}
                      icon={totalAvailable === 0 ? <WarningOutlined /> : undefined}
                      style={{ fontSize: 12, margin: 0, minWidth: 46, textAlign: 'center' }}
                    >
                      {totalAvailable}
                    </Tag>
                  </div>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    {rec ? (
                      <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap' }}>
                        <Text style={{ color: colors.text.secondary, fontSize: 12, fontWeight: 500 }}>
                          {rec.warehouseName}
                        </Text>
                        {rec.branchCity && (
                          <Text style={{ color: colors.text.placeholder, fontSize: 11 }}>· {rec.branchCity}</Text>
                        )}
                        <Tag color={rec.canFullyFulfill ? 'green' : 'orange'} style={{ fontSize: 11, margin: 0 }}>
                          {rec.availableQty} avail{!rec.canFullyFulfill ? ' (partial)' : ''}
                        </Tag>
                      </div>
                    ) : (
                      <Text style={{ color: '#ef4444', fontSize: 12 }}>
                        <WarningOutlined style={{ marginRight: 4 }} />No stock
                      </Text>
                    )}
                  </div>
                </div>
              );
            })}
            {!approveWhLoading && (!approveAvailability || approveAvailability.items.length === 0) && (
              <div style={{ padding: '8px 12px' }}>
                <Text style={{ color: colors.text.placeholder, fontSize: 12 }}>No warehouse stock data.</Text>
              </div>
            )}
          </div>
        )}

        <div style={{ marginTop: 12 }}>
          <Text style={{ fontSize: 12, color: colors.text.secondary }}>Notes (optional)</Text>
          <Input.TextArea
            rows={2}
            maxLength={500}
            value={approveNotes}
            onChange={(e) => setApproveNotes(e.target.value)}
            style={{ marginTop: 4 }}
          />
        </div>
      </Modal>

      {/* ── Picking Slip Modal ───────────────────────────────────────────── */}
      <Modal
        title={`Picking Slip — ${slipTarget?.number ?? ''}`}
        open={!!slipTarget}
        onCancel={() => { setSlipTarget(null); setSlipSelections({}); }}
        footer={[
          <Button key="close" onClick={() => { setSlipTarget(null); setSlipSelections({}); }}>Close</Button>,
          <Button
            key="print"
            type="primary"
            icon={<PrinterOutlined />}
            disabled={computedPickupGroups.length === 0}
            onClick={() => printPickingSlip(computedPickupGroups, slipTarget?.number ?? null, slipTarget?.branchName ?? null)}
          >
            Print Picking Slip
          </Button>,
        ]}
        width={700}
        destroyOnClose
      >
        {slipLoading && <div style={{ textAlign: 'center', padding: 32 }}><Text style={{ color: colors.text.placeholder }}>Loading warehouse data…</Text></div>}
        {slipAvailability && (
          <>
            <div style={{ marginBottom: 12, display: 'flex', alignItems: 'center', gap: 16 }}>
              <Text style={{ color: colors.text.placeholder }}>
                Deliver to: <Text strong style={{ color: colors.text.primary }}>{slipAvailability.destinationBranch ?? slipTarget?.branchName ?? '—'}</Text>
              </Text>
            </div>

            {/* ── Per-product warehouse selector ── */}
            <div style={{ border: `1px solid ${colors.border}`, borderRadius: 6, overflow: 'hidden', marginBottom: 20 }}>
              <div style={{ padding: '8px 12px', borderBottom: `1px solid ${colors.border}` }}>
                <Text strong style={{ color: colors.text.primary, fontSize: 13 }}>Select warehouse per product</Text>
                <Text style={{ color: colors.text.placeholder, fontSize: 12, marginLeft: 8 }}>System suggests the best option — change if needed</Text>
              </div>
              {slipAvailability.items.map((item, idx) => {
                const selectedWhId = slipSelections[item.itemId] ?? item.recommendation?.warehouseId;
                const selectedWh = item.warehouses.find((w) => w.warehouseId === selectedWhId);
                const isLast = idx === slipAvailability.items.length - 1;
                return (
                  <div key={item.itemId} style={{ padding: '8px 12px', borderBottom: isLast ? 'none' : `1px solid ${colors.border}` }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' }}>
                      <div style={{ flex: 1, minWidth: 120 }}>
                        <Text style={{ color: colors.text.primary, fontWeight: 600, fontSize: 13 }}>{item.productName}</Text>
                        <Text style={{ color: colors.text.placeholder, fontSize: 11 }}> · need {item.neededQty} {item.productUom}</Text>
                      </div>
                      <Select
                        size="small"
                        style={{ minWidth: 260 }}
                        value={selectedWhId}
                        onChange={(v) => setSlipSelections((prev) => ({ ...prev, [item.itemId]: v }))}
                        options={item.warehouses.map((w) => ({
                          value: w.warehouseId,
                          label: `${w.warehouseName} (${w.branchName}) — ${w.quantity} in stock`,
                          disabled: w.quantity === 0,
                        }))}
                      />
                      {selectedWh && (
                        <Tag
                          color={selectedWh.quantity >= item.neededQty ? 'green' : selectedWh.quantity > 0 ? 'orange' : 'red'}
                          style={{ fontSize: 11 }}
                        >
                          {selectedWh.quantity} avail
                        </Tag>
                      )}
                    </div>
                    {selectedWh && (selectedWh.branchAddress || selectedWh.branchCity) && (
                      <Text style={{ color: colors.text.placeholder, fontSize: 11, marginTop: 2, display: 'block', paddingLeft: 2 }}>
                        {selectedWh.branchAddress}{selectedWh.branchAddress && selectedWh.branchCity ? ', ' : ''}{selectedWh.branchCity}
                        {selectedWh.branchPhone ? ` · ${selectedWh.branchPhone}` : ''}
                      </Text>
                    )}
                  </div>
                );
              })}
            </div>

            {/* ── Pickup groups summary (recomputed from selections) ── */}
            {computedPickupGroups.length === 0 ? (
              <div style={{ padding: '16px', textAlign: 'center', border: `1px solid ${colors.border}`, borderRadius: 6 }}>
                <WarningOutlined style={{ color: '#f97316', fontSize: 20, marginBottom: 6, display: 'block' }} />
                <Text style={{ color: colors.text.placeholder }}>No warehouse has stock for this indent.</Text>
              </div>
            ) : (
              <>
                <Text style={{ color: colors.text.secondary, fontSize: 12, display: 'block', marginBottom: 8 }}>Driver pickup summary:</Text>
                {computedPickupGroups.map((g) => (
                <div key={g.warehouseId} style={{ marginBottom: 12, border: `1px solid ${colors.border}`, borderRadius: 6, overflow: 'hidden' }}>
                  <div style={{ padding: '8px 12px', borderBottom: `1px solid ${colors.border}`, display: 'flex', alignItems: 'flex-start', gap: 10 }}>
                    <div style={{ flex: 1 }}>
                      <Text style={{ fontWeight: 700, fontSize: 13, color: colors.text.primary }}>{g.warehouseName}</Text>
                      <Text style={{ fontSize: 12, color: colors.text.placeholder }}> · {g.branchName}</Text>
                      {(g.branchAddress || g.branchCity) && (
                        <div style={{ fontSize: 11, color: colors.text.placeholder, marginTop: 1 }}>
                          {g.branchAddress}{g.branchAddress && g.branchCity ? ', ' : ''}{g.branchCity}
                          {g.branchPhone ? ` · ${g.branchPhone}` : ''}
                        </div>
                      )}
                    </div>
                    <Tag color="blue" style={{ fontSize: 11 }}>{g.items.length} item{g.items.length > 1 ? 's' : ''}</Tag>
                  </div>
                  <div style={{ padding: '6px 12px' }}>
                    {g.items.map((item, i) => (
                      <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8, paddingTop: i > 0 ? 5 : 0, paddingBottom: 5, borderBottom: i < g.items.length - 1 ? `1px solid ${colors.border}` : 'none' }}>
                        <div style={{ flex: 1 }}>
                          <Text style={{ color: colors.text.primary, fontSize: 13 }}>{item.productName}</Text>
                          <Text style={{ color: colors.text.placeholder, fontSize: 11 }}> · {item.productSku}</Text>
                        </div>
                        <Text style={{ color: colors.text.placeholder, fontSize: 11 }}>{item.productUom}</Text>
                        <Tag color="blue" style={{ fontWeight: 700, minWidth: 50, textAlign: 'center' }}>Ã— {item.pickQty}</Tag>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </>
          )}
        </>
      )}
      </Modal>

      {/* ── Dispatch Modal ────────────────────────────────────────────────── */}
      <Modal
        title={`Dispatch — ${dispatchTarget?.number ?? ''} to ${dispatchTarget?.branchName ?? ''}`}
        open={!!dispatchTarget}
        onCancel={() => { setDispatchTarget(null); setDispatchSelections({}); dispatchForm.resetFields(); }}
        footer={[
          <Button key="cancel" onClick={() => { setDispatchTarget(null); setDispatchSelections({}); dispatchForm.resetFields(); }}>
            Cancel
          </Button>,
          hasInsufficientStock && (
            <Button key="create-po" type="primary" icon={<ShoppingCartOutlined />} onClick={openPoModal}>
              Order Stock (Create PO)
            </Button>
          ),
          <Button
            key="dispatch"
            type="primary"
            icon={<SendOutlined />}
            disabled={hasInsufficientStock}
            loading={indentAction.isPending}
            onClick={handleDispatch}
          >
            Dispatch
          </Button>,
        ].filter(Boolean)}
        width={720}
        destroyOnClose
      >
        <Form form={dispatchForm} layout="vertical">
          {/* Per-item warehouse selection */}
          {dispatchTarget && (
            <div style={{ marginBottom: 16, border: `1px solid ${colors.border}`, borderRadius: 6, overflow: 'hidden' }}>
              <div style={{ display: 'flex', alignItems: 'center', padding: '8px 12px', borderBottom: `1px solid ${colors.border}`, gap: 8 }}>
                <Space>
                  <Text strong style={{ color: colors.text.primary }}>Pick Warehouse per Product</Text>
                  {warehouseLoading && <Text style={{ color: colors.text.placeholder, fontSize: 12 }}>Checking…</Text>}
                </Space>
              </div>
              {warehouseAvailability?.items.map((avail, idx) => {
                const selectedWhId = dispatchSelections[avail.itemId] ?? avail.recommendation?.warehouseId;
                const selectedWh = avail.warehouses.find((w) => w.warehouseId === selectedWhId);
                const available = selectedWh?.quantity ?? null;
                const canFulfill = available != null && available >= avail.neededQty;
                const isLast = idx === warehouseAvailability.items.length - 1;
                return (
                  <div key={avail.itemId} style={{ padding: '8px 12px', borderBottom: isLast ? 'none' : `1px solid ${colors.border}` }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' }}>
                      <div style={{ flex: 1, minWidth: 100 }}>
                        <Text style={{ color: colors.text.primary, fontWeight: 600, fontSize: 13 }}>{avail.productName}</Text>
                        <Text style={{ color: colors.text.placeholder, fontSize: 11 }}> · need {avail.neededQty}</Text>
                      </div>
                      <Select
                        size="small"
                        style={{ minWidth: 260 }}
                        value={selectedWhId}
                        onChange={(v) => setDispatchSelections((prev) => ({ ...prev, [avail.itemId]: v }))}
                        options={avail.warehouses.map((w) => ({
                          value: w.warehouseId,
                          label: `${w.warehouseName} (${w.branchName}) — ${w.quantity} in stock${avail.recommendation?.warehouseId === w.warehouseId ? ' ★' : ''}`,
                          disabled: w.quantity === 0,
                        }))}
                      />
                      {available != null ? (
                        <Tag color={canFulfill ? 'green' : 'red'} style={{ fontSize: 11 }}>
                          {canFulfill ? null : <WarningOutlined style={{ marginRight: 3 }} />}
                          {available} avail
                        </Tag>
                      ) : (
                        <Tag color="default" style={{ fontSize: 11 }}>No data</Tag>
                      )}
                    </div>
                    {selectedWh && (selectedWh.branchAddress || selectedWh.branchCity) && (
                      <Text style={{ color: colors.text.placeholder, fontSize: 11, marginTop: 2, display: 'block', paddingLeft: 2 }}>
                        {selectedWh.branchAddress}{selectedWh.branchAddress && selectedWh.branchCity ? ', ' : ''}{selectedWh.branchCity}
                        {selectedWh.branchPhone ? ` · ${selectedWh.branchPhone}` : ''}
                      </Text>
                    )}
                  </div>
                );
              })}
              {!warehouseLoading && (!warehouseAvailability || warehouseAvailability.items.length === 0) && (
                <div style={{ padding: '8px 12px' }}>
                  <Text style={{ color: colors.text.placeholder, fontSize: 12 }}>No warehouse stock data.</Text>
                </div>
              )}
            </div>
          )}

          <Form.Item name="dispatchMethod" label="Dispatch Method" rules={[{ required: true, message: 'Select a dispatch method' }]}>
            <Select options={DISPATCH_METHOD_OPTIONS} placeholder="Select how stock will be transported" />
          </Form.Item>

          {/* Company Vehicle */}
          {selectedDispatchMethod === 'company_vehicle' && (
            <Row gutter={12}>
              <Col span={12}>
                <Form.Item name="vehicleNumber" label="Vehicle Number">
                  <Input maxLength={20} placeholder="e.g. TS09 AB 1234" />
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item name="driverName" label="Driver Name">
                  <Input maxLength={100} />
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item name="driverMobile" label="Driver Mobile">
                  <Input maxLength={15} placeholder="+91 9876543210" />
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item name="expectedDeliveryAt" label="Expected Delivery">
                  <DatePicker showTime style={{ width: '100%' }} />
                </Form.Item>
              </Col>
            </Row>
          )}

          {/* Branch Staff Pickup */}
          {selectedDispatchMethod === 'branch_staff_pickup' && (
            <Row gutter={12}>
              <Col span={12}>
                <Form.Item name="driverName" label="Employee Name">
                  <Input maxLength={100} />
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item name="pickupEmployeeId" label="Employee ID">
                  <Input maxLength={50} />
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item name="driverMobile" label="Mobile Number">
                  <Input maxLength={15} placeholder="+91 9876543210" />
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item name="expectedDeliveryAt" label="Pickup Time">
                  <DatePicker showTime style={{ width: '100%' }} />
                </Form.Item>
              </Col>
            </Row>
          )}

          {/* Porter / Rapido / Courier */}
          {(selectedDispatchMethod === 'porter' || selectedDispatchMethod === 'rapido' || selectedDispatchMethod === 'courier') && (
            <Row gutter={12}>
              <Col span={12}>
                <Form.Item name="providerName" label="Provider Name">
                  <Input maxLength={100} placeholder="e.g. Porter, Dunzo, BlueDart" />
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item name="trackingNumber" label="Booking / Tracking ID">
                  <Input maxLength={100} />
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item name="driverName" label="Delivery Person Name">
                  <Input maxLength={100} placeholder="Optional" />
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item name="driverMobile" label="Mobile Number">
                  <Input maxLength={15} placeholder="+91 9876543210" />
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item name="deliveryCharges" label="Delivery Charges (₹)">
                  <InputNumber min={0} precision={2} style={{ width: '100%' }} placeholder="0.00" />
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item name="expectedDeliveryAt" label="Expected Delivery">
                  <DatePicker showTime style={{ width: '100%' }} />
                </Form.Item>
              </Col>
            </Row>
          )}

          {/* Other */}
          {selectedDispatchMethod === 'other' && (
            <Row gutter={12}>
              <Col span={24}>
                <Form.Item name="customMethodName" label="Transport Method" rules={[{ required: true, message: 'Please describe the transport method' }]}>
                  <Input maxLength={100} placeholder="e.g. Staff personal vehicle, auto-rickshaw…" />
                </Form.Item>
              </Col>
            </Row>
          )}

          {/* Notes / Remarks — shown for all methods */}
          {selectedDispatchMethod && (
            <Form.Item name="deliveryNotes" label={selectedDispatchMethod === 'other' ? 'Remarks' : 'Notes (optional)'}>
              <Input.TextArea rows={2} maxLength={500} />
            </Form.Item>
          )}

          {hasInsufficientStock && (
            <Alert
              type="error"
              showIcon
              icon={<WarningOutlined />}
              style={{ marginBottom: 12 }}
              message="Insufficient stock — dispatch blocked"
              description={
                <div>
                  <div style={{ marginBottom: 6 }}>The following products do not have enough stock in the selected warehouse:</div>
                  <ul style={{ margin: 0, paddingLeft: 18 }}>
                    {insufficientItems.map((item) => {
                      const selectedWhId = dispatchSelections[item.itemId] ?? item.recommendation?.warehouseId;
                      const wh = item.warehouses.find((w) => w.warehouseId === selectedWhId);
                      return (
                        <li key={item.itemId}>
                          <strong>{item.productName}</strong> — need <strong>{item.neededQty}</strong>, available: <strong>{wh?.quantity ?? 0}</strong>
                        </li>
                      );
                    })}
                  </ul>
                  <div style={{ marginTop: 8 }}>Click <strong>Order Stock (Create PO)</strong> below to raise a Purchase Order. After the GRN is received, come back here to dispatch.</div>
                </div>
              }
            />
          )}

          <div style={{ marginBottom: 12, border: `1px solid ${colors.border}`, borderRadius: 6, overflow: 'hidden' }}>
            <div style={{ padding: '8px 12px', borderBottom: `1px solid ${colors.border}` }}>
              <Text strong style={{ color: colors.text.primary }}>Dispatch Quantities</Text>
            </div>
            {dispatchTarget?.items.map((it, idx) => (
              <div key={it.id} style={{ display: 'flex', gap: 8, alignItems: 'center', padding: '8px 12px', borderBottom: idx < (dispatchTarget.items.length - 1) ? `1px solid ${colors.border}` : 'none' }}>
                <div style={{ flex: 2 }}>
                  <Text style={{ fontWeight: 600, color: colors.text.primary }}>{it.product.name}</Text>
                  <Text style={{ color: colors.text.placeholder, fontSize: 12 }}> · {it.product.uom}</Text>
                </div>
                <Text style={{ color: colors.text.placeholder, fontSize: 12, minWidth: 90 }}>Approved: <strong style={{ color: colors.text.primary }}>{it.approvedQty ?? it.requestedQty}</strong></Text>
                <Form.Item name={['items', idx, 'fulfilledQty']} label={idx === 0 ? 'Qty' : undefined}
                  rules={[{ required: true, type: 'number', min: 0 }]} style={{ marginBottom: 0, minWidth: 100 }}>
                  <InputNumber min={0} max={it.approvedQty ?? it.requestedQty} style={{ width: '100%' }} />
                </Form.Item>
              </div>
            ))}
          </div>
        </Form>
      </Modal>

      {/* ── Create PO Modal ───────────────────────────────────────────────── */}
      <Modal
        title={`Order Stock — ${poIndentRef?.number ?? ''}`}
        open={poModalOpen}
        onCancel={() => { setPoModalOpen(false); poForm.resetFields(); }}
        onOk={handleCreatePO}
        okText={<><ShoppingCartOutlined /> Create Purchase Order</>}
        confirmLoading={createPO.isPending}
        width={680}
        destroyOnClose
      >
        <Alert
          type="info"
          showIcon
          style={{ marginBottom: 16 }}
          message="This will create a Purchase Order to restock your warehouse. After receiving the GRN, return to this stock request to dispatch."
        />
        <Form form={poForm} layout="vertical">
          <Row gutter={12}>
            <Col span={12}>
              <Form.Item name="branchId" label="Deliver Stock To (Branch)" rules={[{ required: true, message: 'Select the branch / warehouse to receive stock' }]}>
                <Select
                  showSearch
                  options={branchOptions}
                  placeholder="Select branch"
                  filterOption={(i, o) => (o?.label ?? '').toLowerCase().includes(i.toLowerCase())}
                />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="supplierId" label="Supplier" rules={[{ required: true, message: 'Select a supplier' }]}>
                <Select
                  showSearch
                  options={supplierOptions}
                  placeholder="Select supplier"
                  filterOption={(i, o) => (o?.label ?? '').toLowerCase().includes(i.toLowerCase())}
                />
              </Form.Item>
            </Col>
          </Row>

          <div style={{ border: `1px solid ${colors.border}`, borderRadius: 6, overflow: 'hidden', marginBottom: 12 }}>
            <div style={{ padding: '8px 12px', borderBottom: `1px solid ${colors.border}` }}>
              <Text strong style={{ color: colors.text.primary }}>Items to Order</Text>
              <Text style={{ color: colors.text.placeholder, fontSize: 12, marginLeft: 8 }}>Unit price and tax are optional — fill them in or leave as 0</Text>
            </div>
            <Form.List name="items">
              {(fields) => (
                <div>
                  {fields.map((field, idx) => {
                    const item = poItemsForOrder[idx];
                    return (
                      <div key={field.key} style={{ padding: '10px 12px', borderBottom: idx < fields.length - 1 ? `1px solid ${colors.border}` : 'none' }}>
                        <div style={{ marginBottom: 8 }}>
                          <Text style={{ fontWeight: 600, color: colors.text.primary }}>{item?.productName}</Text>
                          <Text style={{ color: colors.text.placeholder, fontSize: 12 }}> · {item?.productSku} · {item?.productUom}</Text>
                        </div>
                        <Form.Item name={[field.name, 'productId']} hidden><Input /></Form.Item>
                        <Row gutter={8}>
                          <Col span={8}>
                            <Form.Item name={[field.name, 'quantity']} label="Qty to Order" rules={[{ required: true, type: 'number', min: 1 }]} style={{ marginBottom: 0 }}>
                              <InputNumber min={1} style={{ width: '100%' }} />
                            </Form.Item>
                          </Col>
                          <Col span={8}>
                            <Form.Item name={[field.name, 'unitPrice']} label="Unit Price (₹)" style={{ marginBottom: 0 }}>
                              <InputNumber min={0} precision={2} style={{ width: '100%' }} placeholder="0.00" />
                            </Form.Item>
                          </Col>
                          <Col span={8}>
                            <Form.Item name={[field.name, 'taxRate']} label="Tax (%)" style={{ marginBottom: 0 }}>
                              <InputNumber min={0} max={100} precision={2} style={{ width: '100%' }} placeholder="0" />
                            </Form.Item>
                          </Col>
                        </Row>
                      </div>
                    );
                  })}
                </div>
              )}
            </Form.List>
          </div>

          <Form.Item name="notes" label="Notes">
            <Input.TextArea rows={2} maxLength={500} />
          </Form.Item>
        </Form>
      </Modal>

    </div>
  );
}


