/**
 * Dummy data for the Admin → Reports → Calls & Media → Walk-In Details screen.
 *
 * Each row is one customer who physically walked into a branch — they may or
 * may not have an existing enquiry on file. Outcome describes what happened
 * at reception (booked a service, just consulted, asked to be followed up,
 * left without action).
 *
 * Branch and category names line up with the rows seeded by
 * `seed-admin-showcase.ts`.
 */

export type WalkInOutcome = 'Booked' | 'Consultation' | 'Follow-Up' | 'Lost' | 'Pending';

export interface WalkInRow {
  key: string;
  walkInAt: string;              // ISO timestamp
  branchName: string;
  customerName: string;
  mobileNumber: string;
  gender: 'Male' | 'Female';
  treatmentInterest: string;
  category: string;
  source: string;                // Media: how they heard about the clinic
  attendedBy: string;            // Front-desk staff
  outcome: WalkInOutcome;
  remarks: string;
}

export const WALK_IN_ROWS: WalkInRow[] = [
  {
    key: 'WI-0001',
    walkInAt: '2026-05-21T10:15:00',
    branchName: 'Jubilee Hills',
    customerName: 'Aarav Mehta',
    mobileNumber: '+91 98112 70011',
    gender: 'Male',
    treatmentInterest: 'TCA Peel',
    category: 'Skin Services',
    source: 'Instagram',
    attendedBy: 'Anita Reddy',
    outcome: 'Booked',
    remarks: 'Booked 4-session course on the spot',
  },
  {
    key: 'WI-0002',
    walkInAt: '2026-05-21T11:00:00',
    branchName: 'Banjara Hills',
    customerName: 'Priya Kapoor',
    mobileNumber: '+91 98100 10002',
    gender: 'Female',
    treatmentInterest: 'Laser - Full Legs',
    category: 'LASER',
    source: 'Website',
    attendedBy: 'Divya Rao',
    outcome: 'Consultation',
    remarks: 'Patch test scheduled for next week',
  },
  {
    key: 'WI-0003',
    walkInAt: '2026-05-21T12:20:00',
    branchName: 'Bandra West',
    customerName: 'Karthik Iyer',
    mobileNumber: '+91 98200 10003',
    gender: 'Male',
    treatmentInterest: 'PRP Hair Therapy',
    category: 'Hair Care',
    source: 'Referral',
    attendedBy: 'Karthik Iyer',
    outcome: 'Follow-Up',
    remarks: 'Wants to discuss with family',
  },
  {
    key: 'WI-0004',
    walkInAt: '2026-05-20T09:45:00',
    branchName: 'Koramangala',
    customerName: 'Anita Reddy',
    mobileNumber: '+91 98300 10004',
    gender: 'Female',
    treatmentInterest: 'Pumpkin Peel',
    category: 'Skin Services',
    source: 'Whatsapp',
    attendedBy: 'Anita Reddy',
    outcome: 'Booked',
    remarks: '-',
  },
  {
    key: 'WI-0005',
    walkInAt: '2026-05-20T11:30:00',
    branchName: 'Connaught Place',
    customerName: 'Vikram Singh',
    mobileNumber: '+91 98111 10005',
    gender: 'Male',
    treatmentInterest: 'Wellness Membership',
    category: 'Wellness',
    source: 'Referral',
    attendedBy: 'Vikram Singh',
    outcome: 'Booked',
    remarks: 'Annual plan signed',
  },
  {
    key: 'WI-0006',
    walkInAt: '2026-05-20T15:00:00',
    branchName: 'Powai',
    customerName: 'Meera Joshi',
    mobileNumber: '+91 98220 10006',
    gender: 'Female',
    treatmentInterest: 'Laser - Half Legs',
    category: 'LASER',
    source: 'Instagram',
    attendedBy: 'Meera Joshi',
    outcome: 'Booked',
    remarks: '5-session course booked',
  },
  {
    key: 'WI-0007',
    walkInAt: '2026-05-19T10:00:00',
    branchName: 'Indiranagar',
    customerName: 'Arjun Mehta',
    mobileNumber: '+91 98445 10007',
    gender: 'Male',
    treatmentInterest: 'Product Consultation',
    category: 'Products',
    source: 'Walk-in',
    attendedBy: 'Arjun Mehta',
    outcome: 'Booked',
    remarks: 'Purchased Cerascape cleanser + Melarid serum',
  },
  {
    key: 'WI-0008',
    walkInAt: '2026-05-19T13:45:00',
    branchName: 'Anna Nagar',
    customerName: 'Sneha Iyer',
    mobileNumber: '+91 98445 10008',
    gender: 'Female',
    treatmentInterest: 'Under-Eye Peel',
    category: 'Skin Services',
    source: 'Sms',
    attendedBy: 'Sneha Iyer',
    outcome: 'Follow-Up',
    remarks: 'Will return after price check',
  },
  {
    key: 'WI-0009',
    walkInAt: '2026-05-18T11:15:00',
    branchName: 'Jubilee Hills',
    customerName: 'Rajesh Kumar',
    mobileNumber: '+91 99004 10009',
    gender: 'Male',
    treatmentInterest: 'Trichology Consultation',
    category: 'Hair Care',
    source: 'Youtube',
    attendedBy: 'Anita Reddy',
    outcome: 'Consultation',
    remarks: 'Booked first session at consultation',
  },
  {
    key: 'WI-0010',
    walkInAt: '2026-05-18T16:30:00',
    branchName: 'Banjara Hills',
    customerName: 'Divya Rao',
    mobileNumber: '+91 99004 10010',
    gender: 'Female',
    treatmentInterest: 'Minor Skin Surgery',
    category: 'Skin Services',
    source: 'Referral',
    attendedBy: 'Divya Rao',
    outcome: 'Booked',
    remarks: 'Procedure scheduled',
  },
  {
    key: 'WI-0011',
    walkInAt: '2026-05-17T10:30:00',
    branchName: 'Jubilee Hills',
    customerName: 'Rohan Kapoor',
    mobileNumber: '+91 98100 11111',
    gender: 'Male',
    treatmentInterest: 'TCA Peel',
    category: 'Skin Services',
    source: 'Whatsapp',
    attendedBy: 'Anita Reddy',
    outcome: 'Pending',
    remarks: 'Awaiting doctor availability',
  },
  {
    key: 'WI-0012',
    walkInAt: '2026-05-17T14:00:00',
    branchName: 'Powai',
    customerName: 'Anita Desai',
    mobileNumber: '+91 98200 33333',
    gender: 'Female',
    treatmentInterest: 'Take-home Products',
    category: 'Products',
    source: 'Instagram',
    attendedBy: 'Meera Joshi',
    outcome: 'Booked',
    remarks: 'Shampoo + multivitamins',
  },
  {
    key: 'WI-0013',
    walkInAt: '2026-05-16T09:20:00',
    branchName: 'Bandra West',
    customerName: 'Sahil Khanna',
    mobileNumber: '+91 98111 60002',
    gender: 'Male',
    treatmentInterest: 'Laser - Upper Lip',
    category: 'LASER',
    source: 'Website',
    attendedBy: 'Karthik Iyer',
    outcome: 'Booked',
    remarks: '-',
  },
  {
    key: 'WI-0014',
    walkInAt: '2026-05-16T12:00:00',
    branchName: 'Koramangala',
    customerName: 'Deepak Menon',
    mobileNumber: '+91 98200 60005',
    gender: 'Male',
    treatmentInterest: 'PRP Hair Therapy',
    category: 'Hair Care',
    source: 'Pamphlet',
    attendedBy: 'Anita Reddy',
    outcome: 'Booked',
    remarks: '8-session bundle',
  },
  {
    key: 'WI-0015',
    walkInAt: '2026-05-15T15:30:00',
    branchName: 'Connaught Place',
    customerName: 'Pooja Sharma',
    mobileNumber: '+91 98112 70010',
    gender: 'Female',
    treatmentInterest: 'Wellness Membership',
    category: 'Wellness',
    source: 'Referral',
    attendedBy: 'Vikram Singh',
    outcome: 'Booked',
    remarks: 'Family annual plan',
  },
  {
    key: 'WI-0016',
    walkInAt: '2026-05-15T17:00:00',
    branchName: 'Indiranagar',
    customerName: 'Neha Bansal',
    mobileNumber: '+91 99220 44444',
    gender: 'Female',
    treatmentInterest: 'Pumpkin Peel',
    category: 'Skin Services',
    source: 'Instagram',
    attendedBy: 'Arjun Mehta',
    outcome: 'Lost',
    remarks: 'Price concern; left without booking',
  },
  {
    key: 'WI-0017',
    walkInAt: '2026-05-14T10:00:00',
    branchName: 'Anna Nagar',
    customerName: 'Rahul Verma',
    mobileNumber: '+91 99550 11122',
    gender: 'Male',
    treatmentInterest: 'Laser - Full Legs',
    category: 'LASER',
    source: 'Lead in Landline',
    attendedBy: 'Sneha Iyer',
    outcome: 'Consultation',
    remarks: 'Wants to compare with another clinic',
  },
  {
    key: 'WI-0018',
    walkInAt: '2026-05-14T13:15:00',
    branchName: 'Jubilee Hills',
    customerName: 'Ishita Nair',
    mobileNumber: '+91 90880 22233',
    gender: 'Female',
    treatmentInterest: 'Take-home Products',
    category: 'Products',
    source: 'Walk-in',
    attendedBy: 'Anita Reddy',
    outcome: 'Booked',
    remarks: 'Routine product reorder',
  },
  {
    key: 'WI-0019',
    walkInAt: '2026-05-13T11:30:00',
    branchName: 'Powai',
    customerName: 'Manish Gupta',
    mobileNumber: '+91 90110 33344',
    gender: 'Male',
    treatmentInterest: 'TCA + Under-Eye combo',
    category: 'Skin Services',
    source: 'Whatsapp',
    attendedBy: 'Meera Joshi',
    outcome: 'Follow-Up',
    remarks: 'Wants spouse to come along next time',
  },
  {
    key: 'WI-0020',
    walkInAt: '2026-05-13T16:45:00',
    branchName: 'Banjara Hills',
    customerName: 'Karan Malhotra',
    mobileNumber: '+91 90008 77788',
    gender: 'Male',
    treatmentInterest: 'Wellness — Family Plan',
    category: 'Wellness',
    source: 'Instagram',
    attendedBy: 'Divya Rao',
    outcome: 'Booked',
    remarks: 'Annual plan + onboarding scheduled',
  },
];
